<!DOCTYPE html>
<html>

<head>

    <meta charset="UTF-8">

    <title>Daily Work Report</title>

    <style>

        body{
            font-family: DejaVu Sans;
            font-size:12px;
            color:#333;
        }

        .header{
            text-align:center;
            border-bottom:2px solid #0d6efd;
            padding-bottom:10px;
            margin-bottom:20px;
        }

        .header h1{
            margin:0;
            color:#0d6efd;
            font-size:24px;
        }

        .header h3{
            margin-top:5px;
            font-size:18px;
        }

        table{
            width:100%;
            border-collapse:collapse;
        }

        table,
        th,
        td{
            border:1px solid #000;
        }

        th{
            background:#0d6efd;
            color:white;
            padding:8px;
            text-align:center;
        }

        td{
            padding:7px;
            text-align:center;
        }

        tbody tr:nth-child(even){
            background:#f5f5f5;
        }

        .footer{
            margin-top:20px;
            text-align:center;
            color:#777;
            font-size:11px;
        }

    </style>

</head>

<body>

<div class="header">

    <h1>Project Management System</h1>

    <h3>Daily Work Report</h3>

</div>

<p>

<strong>Generated Date :</strong>

{{ now()->format('d M Y') }}

&nbsp;&nbsp;&nbsp;&nbsp;

<strong>Generated Time :</strong>

{{ now()->format('h:i A') }}

</p>

<table>

<thead>

<tr>

<th>ID</th>

<th>Project</th>

<th>Employee</th>

<th>Today's Work</th>

<th>Work Date</th>

<th>Created</th>

</tr>

</thead>

<tbody>

@foreach($dailyUpdates as $update)

<tr>

<td>{{ $update->id }}</td>

<td>{{ optional($update->project)->title }}</td>

<td>{{ optional($update->user)->name }}</td>

<td>{{ $update->work_update }}</td>

<td>

{{ \Carbon\Carbon::parse($update->work_date)->format('d M Y') }}

</td>

<td>

{{ $update->created_at->format('d M Y') }}

</td>

</tr>

@endforeach

</tbody>

</table>

<div class="footer">

Generated by Project Management System

</div>

</body>

</html>