<!DOCTYPE html>
<html>

<head>

    <meta charset="UTF-8">

    <title>Group Chat Report</title>

    <style>

        body{
            font-family: DejaVu Sans;
            font-size:12px;
            color:#333;
        }

        .header{
            text-align:center;
            border-bottom:2px solid #0d6efd;
            padding-bottom:10px;
            margin-bottom:20px;
        }

        .header h1{
            margin:0;
            color:#0d6efd;
            font-size:24px;
        }

        .header h3{
            margin-top:5px;
            font-size:18px;
        }

        table{
            width:100%;
            border-collapse:collapse;
        }

        table,
        th,
        td{
            border:1px solid #000;
        }

        th{
            background:#0d6efd;
            color:#fff;
            padding:8px;
            text-align:center;
        }

        td{
            padding:7px;
            text-align:center;
            vertical-align:middle;
        }

        tbody tr:nth-child(even){
            background:#f5f5f5;
        }

        .footer{
            margin-top:20px;
            text-align:center;
            color:#777;
            font-size:11px;
        }

    </style>

</head>

<body>

<div class="header">

    <h1>Project Management System</h1>

    <h3>Group Chat Report</h3>

</div>

<p>

<strong>Generated Date :</strong>

{{ now()->format('d M Y') }}

&nbsp;&nbsp;&nbsp;&nbsp;

<strong>Generated Time :</strong>

{{ now()->format('h:i A') }}

</p>

<table>

<thead>

<tr>

<th>ID</th>

<th>Group</th>

<th>Sender</th>

<th>Message</th>

<th>Attachment</th>

<th>Date</th>

<th>Time</th>

</tr>

</thead>

<tbody>

@foreach($groupMessages as $message)

<tr>

<td>{{ $message->id }}</td>

<td>{{ optional($message->group)->name }}</td>

<td>{{ optional($message->user)->name }}</td>

<td>{{ \Illuminate\Support\Str::limit(strip_tags($message->message),40) }}</td>

<td>

@if($message->file)

Yes

@else

No

@endif

</td>

<td>

{{ $message->created_at->format('d M Y') }}

</td>

<td>

{{ $message->created_at->format('h:i A') }}

</td>

</tr>

@endforeach

</tbody>

</table>

<div class="footer">

Generated by Project Management System

</div>

</body>

</html>