<!DOCTYPE html>
<html>

<head>

    <meta charset="UTF-8">

    <title>Milestone Report</title>

    <style>

        body{
            font-family: DejaVu Sans;
            font-size:12px;
            color:#333;
        }

        .header{
            text-align:center;
            border-bottom:2px solid #0d6efd;
            padding-bottom:10px;
            margin-bottom:20px;
        }

        .header h1{
            margin:0;
            color:#0d6efd;
            font-size:24px;
        }

        .header h3{
            margin-top:5px;
            font-size:18px;
        }

        table{
            width:100%;
            border-collapse:collapse;
        }

        table,
        th,
        td{
            border:1px solid #000;
        }

        th{
            background:#0d6efd;
            color:white;
            padding:8px;
            text-align:center;
        }

        td{
            padding:7px;
            text-align:center;
        }

        tbody tr:nth-child(even){
            background:#f5f5f5;
        }

        .pending{
            color:red;
            font-weight:bold;
        }

        .progress{
            color:orange;
            font-weight:bold;
        }

        .completed{
            color:green;
            font-weight:bold;
        }

        .footer{

            margin-top:20px;

            text-align:center;

            color:#777;

            font-size:11px;

        }

    </style>

</head>

<body>

<div class="header">

    <h1>Project Management System</h1>

    <h3>Milestone Report</h3>

</div>

<p>

<strong>Generated Date :</strong>

{{ now()->format('d M Y') }}

&nbsp;&nbsp;&nbsp;&nbsp;

<strong>Generated Time :</strong>

{{ now()->format('h:i A') }}

</p>

<table>

<thead>

<tr>

<th>ID</th>

<th>Project</th>

<th>Milestone</th>

<th>Due Date</th>

<th>Status</th>

<th>Created</th>

</tr>

</thead>

<tbody>

@foreach($milestones as $milestone)

<tr>

<td>{{ $milestone->id }}</td>

<td>{{ optional($milestone->project)->title }}</td>

<td>{{ $milestone->title }}</td>

<td>

{{ \Carbon\Carbon::parse($milestone->due_date)->format('d M Y') }}

</td>

<td>

@if($milestone->status=='Pending')

<span class="pending">

Pending

</span>

@elseif($milestone->status=='In Progress')

<span class="progress">

In Progress

</span>

@else

<span class="completed">

Completed

</span>

@endif

</td>

<td>

{{ $milestone->created_at->format('d M Y') }}

</td>

</tr>

@endforeach

</tbody>

</table>

<div class="footer">

Generated by Project Management System

</div>

</body>

</html>