<!DOCTYPE html>
<html>

<head>

    <meta charset="UTF-8">

    <title>Project Status Report</title>

    <style>

        body{
            font-family: DejaVu Sans;
            font-size:12px;
            color:#333;
        }

        .header{
            text-align:center;
            border-bottom:2px solid #0d6efd;
            padding-bottom:10px;
            margin-bottom:20px;
        }

        .header h1{
            margin:0;
            font-size:24px;
            color:#0d6efd;
        }

        .header h3{
            margin:5px 0;
            font-size:18px;
        }

        .info{
            margin-bottom:15px;
        }

        .info table{
            width:100%;
            border:none;
        }

        .info td{
            border:none;
            padding:3px;
        }

        table{
            width:100%;
            border-collapse:collapse;
        }

        table, th, td{
            border:1px solid #000;
        }

        th{
            background:#0d6efd;
            color:#fff;
            padding:8px;
            text-align:center;
        }

        td{
            padding:8px;
            text-align:center;
        }

        tbody tr:nth-child(even){
            background:#f5f5f5;
        }

        .pending{
            color:#dc3545;
            font-weight:bold;
        }

        .progress{
            color:#fd7e14;
            font-weight:bold;
        }

        .completed{
            color:#198754;
            font-weight:bold;
        }

        .footer{
            margin-top:20px;
            text-align:center;
            font-size:11px;
            color:#666;
        }

    </style>

</head>

<body>

<div class="header">

    <h1>Project Management System</h1>

    <h3>Project Status Report</h3>

</div>

<div class="info">

<table>

<tr>

<td>

<strong>Generated Date :</strong>

{{ now()->format('d M Y') }}

</td>

<td align="right">

<strong>Generated Time :</strong>

{{ now()->format('h:i A') }}

</td>

</tr>

<tr>

<td>

<strong>Total Projects :</strong>

{{ $projects->count() }}

</td>

<td></td>

</tr>

</table>

</div>

<table>

<thead>

<tr>

<th>ID</th>

<th>Project</th>

<th>Status</th>

<th>Start Date</th>

<th>Deadline</th>

<th>Budget</th>

</tr>

</thead>

<tbody>

@foreach($projects as $project)

<tr>

<td>{{ $project->id }}</td>

<td>{{ $project->title }}</td>

<td>

@if($project->status == 'Pending')

<span class="pending">Pending</span>

@elseif($project->status == 'In Progress')

<span class="progress">In Progress</span>

@else

<span class="completed">Completed</span>

@endif

</td>

<td>

{{ \Carbon\Carbon::parse($project->start_date)->format('d M Y') }}

</td>

<td>

{{ \Carbon\Carbon::parse($project->deadline)->format('d M Y') }}

</td>

<td>

₹ {{ number_format($project->budget,2) }}

</td>

</tr>

@endforeach

</tbody>

</table>

<div class="footer">

Generated by Project Management System

</div>

</body>

</html>