<!DOCTYPE html>
<html>

<head>

    <meta charset="UTF-8">

    <title>Project Summary Report</title>

    <style>

        body{
            font-family: DejaVu Sans;
            font-size:12px;
            color:#333;
        }

        .header{
            text-align:center;
            border-bottom:2px solid #0d6efd;
            padding-bottom:10px;
            margin-bottom:20px;
        }

        .header h1{
            margin:0;
            font-size:24px;
            color:#0d6efd;
        }

        .header h3{
            margin:5px 0;
            font-size:18px;
        }

        .info{
            margin-bottom:15px;
        }

        .info table{
            width:100%;
            border:none;
        }

        .info td{
            border:none;
            padding:3px;
        }

        table{
            width:100%;
            border-collapse:collapse;
        }

        th{
            background:#0d6efd;
            color:white;
            padding:8px;
            border:1px solid #000;
        }

        td{
            padding:8px;
            border:1px solid #000;
        }

        tbody tr:nth-child(even){
            background:#f2f2f2;
        }

        .footer{
            margin-top:25px;
            text-align:center;
            font-size:11px;
            color:#666;
        }

    </style>

</head>

<body>

<div class="header">

    <h1>Project Management System</h1>

    <h3>Project Summary Report</h3>

</div>

<div class="info">

<table>

<tr>

<td>

<strong>Generated Date :</strong>

{{ now()->format('d M Y') }}

</td>

<td align="right">

<strong>Generated Time :</strong>

{{ now()->format('h:i A') }}

</td>

</tr>

<tr>

<td>

<strong>Total Projects :</strong>

{{ $projects->count() }}

</td>

<td></td>

</tr>

</table>

</div>

<table>

<thead>

<tr>

<th>ID</th>

<th>Project</th>

<th>Status</th>

<th>Budget</th>

<th>Deadline</th>

</tr>

</thead>

<tbody>

@foreach($projects as $project)

<tr>

<td>{{ $project->id }}</td>

<td>{{ $project->title }}</td>

<td>{{ $project->status }}</td>

<td>₹ {{ number_format($project->budget) }}</td>

<td>{{ \Carbon\Carbon::parse($project->deadline)->format('d M Y') }}</td>

</tr>

@endforeach

</tbody>

</table>

<div class="footer">

Generated by Project Management System

</div>

</body>

</html>