<!DOCTYPE html>
<html>

<head>

    <meta charset="UTF-8">

    <title>User Wise Report</title>

    <style>

        body{
            font-family: DejaVu Sans;
            font-size:12px;
            color:#333;
        }

        .header{
            text-align:center;
            border-bottom:2px solid #0d6efd;
            padding-bottom:10px;
            margin-bottom:20px;
        }

        .header h1{
            margin:0;
            font-size:24px;
            color:#0d6efd;
        }

        .header h3{
            margin:5px 0;
            font-size:18px;
        }

        table{
            width:100%;
            border-collapse:collapse;
        }

        table,th,td{
            border:1px solid #000;
        }

        th{
            background:#0d6efd;
            color:#fff;
            padding:8px;
            text-align:center;
        }

        td{
            padding:8px;
            text-align:center;
        }

        tbody tr:nth-child(even){
            background:#f2f2f2;
        }

        .footer{
            margin-top:20px;
            text-align:center;
            font-size:11px;
            color:#666;
        }

    </style>

</head>

<body>

<div class="header">

    <h1>Project Management System</h1>

    <h3>User Wise Report</h3>

</div>

<p>

<strong>Generated Date :</strong>

{{ now()->format('d M Y') }}

&nbsp;&nbsp;&nbsp;&nbsp;

<strong>Generated Time :</strong>

{{ now()->format('h:i A') }}

</p>

<table>

<thead>

<tr>

<th>ID</th>

<th>Name</th>

<th>Email</th>

<th>Role</th>

<th>Assigned Projects</th>

<th>Daily Updates</th>

</tr>

</thead>

<tbody>

@foreach($users as $user)

<tr>

<td>{{ $user->id }}</td>

<td>{{ $user->name }}</td>

<td>{{ $user->email }}</td>

<td>{{ ucfirst($user->role) }}</td>

<td>{{ $user->projects()->count() }}</td>

<td>{{ $user->dailyUpdates()->count() }}</td>

</tr>

@endforeach

</tbody>

</table>

<div class="footer">

Generated by Project Management System

</div>

</body>

</html>